set nord0  2E3440
set nord1  3B4252
set nord2  434C5E
set nord3  4C566A
set nord4  D8DEE9
set nord5  E5E9F0
set nord6  ECEFF4
set nord7  8FBCBB
set nord8  88C0D0
set nord9  81A1C1
set nord10 5E81AC
set nord11 BF616A
set nord12 D08770
set nord13 EBCB8B
set nord14 A3BE8C
set nord15 B48EAD

set fish_pager_color_secondary   $nord1
set fish_color_comment           $nord3
set fish_color_autosuggestion    $nord3
set fish_color_normal            $nord4
set fish_color_param             $nord4
set fish_color_user              $nord4
set fish_color_end               $nord6
set fish_pager_color_completion  $nord6
set fish_color_match             $nord8
set fish_color_cwd               $nord8
set fish_color_command           $nord9
set fish_color_redirection       $nord9
set fish_color_operator          $nord9
set fish_color_host              $nord9
set fish_pager_color_description $nord10
set fish_color_error             $nord11
set fish_pager_color_progress    $nord12
set fish_color_escape            $nord13
set fish_pager_color_prefix      $nord13
set fish_color_quote             $nord14
set fish_color_cancel            $nord15

set fish_color_search_match      --background=$nord1
